#!/usr/bin/bash

[[ ! -d "../Mindustry" ]] && echo "Mindustry source code not found" && exit 1
[[ ! -d "../Mindustry/core/assets-raw/sprites_out" ]] && echo "Sprites not found" && exit 1
[[ ! -d "../Mindustry/core/assets/sprites" ]] && echo "Sprites not found" && exit 1

[[ -d "./assets" ]] && rm -rf "./assets"

echo -n "Copying sprites..."

mkdir "./assets"
cp "../Mindustry/core/assets/sprites/error.png" "./assets"
cp "../Mindustry/core/assets/sprites/sprites.aatls" "./assets"
cp "../Mindustry/core/assets/sprites/schematic-background.png" "./assets"

cp -r "../Mindustry/core/assets-raw/sprites_out" "./assets"
mv "./assets/sprites_out" "./assets/sprites"

cut -c 1-64 <<< `find "../Mindustry/core/assets-raw/sprites_out" -type f | xargs -L 1 sha256sum` | sort | sha256sum | cut -c 1-64 > sprites-hash

echo "Done"
